################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= vector_reduction 
# Cuda source files (compiled with cudacc)
CUFILES		:= vector_reduction.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= vector_reduction_gold.cpp 

################################################################################
# Rules and targets

ROOTDIR = /usr/share/cuda-sdk/C/common
BINDIR = .
include $(ROOTDIR)/common.mk
